version: '2'
services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube-conf:/opt/sonarqube/conf
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    depends_on:
      - postgresql
  
  postgresql:
    image: postgres
    container_name: postgresql
    ports:
      - "5432:5432"
    networks:
      - sonarqube
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql-data:/var/lib/postgresql/data
volumes:
  sonarqube-conf:
    driver: local
  sonarqube-data:
    driver: local
  sonarqube-extensions:
    driver: local
  sonarqube-bundled-plugins:
    driver: local
  postgresql:
    driver: local
  postgresql-data:
    driver: local
networks:
    sonarqube:
      driver: bridge