version: '2'
services:
  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - "80:8080"
    volumes:
      - ../source_code/magento2:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/filebeat/filebeat.yml:/etc/filebeat/filebeat.yml
    depends_on:
      - phpfpm
    networks:
      - website

  # varnish:
  #   build: ./varnish/
  #   container_name: varnish
  #   environment:
  #     - VIRTUAL_HOST=blog.benhall.me.uk
  #     - VARNISH_BACKEND_PORT=80
  #     - VARNISH_BACKEND_HOST=wordpress
  #   networks:
  #     - website

  phpfpm:
    build: ./phpfpm/
    container_name: fpm
    volumes:
      - ../source_code/magento2:/var/www/html
      - ./script:/var/www/html/script
    networks:
      - website

  crontab:
    build: ./crontab/
    container_name: crontab
    volumes:
      - ../source_code/magento2:/var/www/html
    networks:
      - website
  
  mysql:
    image: mysql:5.6
    container_name: mysql
    volumes:
      - "./mysql/mysql56/data:/var/lib/mysql"
      - "./mysql/mysql56/init:/docker-entrypoint-initdb.d"
      # - "./mysql/mysql56/mysql/conf.d:/etc/mysql/conf.d"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento2
      MYSQL_USER: magento2demo
      MYSQL_PASSWORD: magento2demo
    ports:
      - "3306:3306"
    networks:
      - website
networks:
    website:
      driver: bridge