version: '2'
services:
  jenkins:
    image: "jenkinsci/blueocean:1.4.2"
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins:
    driver: local